### PR TITLE
version bug

### PR DESCRIPTION
**Pull request by xiazemin**
$ php -v
PHP 7.2.0-dev (cli) (built: May 20 2020 23:46:30) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

When I build from Xdebug v2.9.6 source,There is a bug 

```
In file included from /Users/didi/PhpstormProjects/c/php-src/ext/xdebug/xdebug-2.9.6/xdebug.c:51:
./php_xdebug.h:147:2: error: unknown type name 'zif_handler'
        zif_handler   orig_var_dump_func;
        ^
./php_xdebug.h:148:2: error: unknown type name 'zif_handler'
        zif_handler   orig_set_time_limit_func;
```

The reason is that,version is not right.

should change 
`# if PHP_VERSION_ID < 70200`
with
`# if PHP_VERSION_ID <= 70200`

change
`#if PHP_VERSION_ID >= 70200`
with 

`#if PHP_VERSION_ID > 70200`

### CODE REVIEW

**Comment by derickr** [comment]
Please don't use Pull Request to file bug reports.

The bug report itself is not actionable. You're saying that a *pre-release* version of PHP 7.2.0 does not compile. I do not support -dev versions of PHP. With your suggested change, Xdebug 2.9.6 no longer compiles with the released PHP 7.2.0 either.
